language: go
sudo: false

go:
  - 1.13

services:
  - postgresql

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10

before_install:
  - psql -U postgres -c "create extension postgis"

env:
  - GO111MODULE=on

script:
  - go install github.com/liucxer/courier/husky
  - husky cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
